### ISSUE TITLE
An ENOENT error due to vite:css.

### ISSUE THREAD

**Issue by gamekaiju** [AR10Dev/tauri-solid-ts-tailwind-vite#63]
No matter what I try, I always get this error:

```
ENOENT: no such file or directory, stat 'index.html'
10:24:34 PM [vite] Internal server error: ENOENT: no such file or directory, stat 'index.html'
  Plugin: vite:css
  File: /home/fernando/Documents/Code/tauri-solid-ts-tailwind-vite/src/index.css
```

By chance do you happen to have an idea why?

It's strange because the build (I think) looks fine. Can you confirm this?

![image](https://user-images.githubusercontent.com/71205864/179857007-7dde087c-d3f0-4580-81f4-e0556af30e14.png)

**Comment by AR10Dev** [comment]
I think maybe it's something under Vite that is going wrong but I can confirm the result is the same. Btw you can try the updated template, it uses Vite v3, maybe it solves the error.

**Comment by gamekaiju** [comment]
Hi @AR10Dev I forgot to update this issue. I don't remember how I fixed it neither. I created a new project using degit, I should have forked it instead. I'll create a pull request with a fix if I can. Thank you!

**Comment by aleroza** [comment]
Hello
I got the same error, but not the same result.
When i'm building app everything works fine, styles are present, but `npm run build` returns this 
![image](https://user-images.githubusercontent.com/48179175/182174903-818325c3-f137-4b06-ba01-81145ecc69d6.png)

**Comment by AR10Dev** [comment]
It's related to Tailwind CSS and there's already a [pull](https://github.com/tailwindlabs/tailwindcss/pull/9032) to fix it

**Comment by AR10Dev** [comment]
tailwindlabs/tailwindcss#9032

**Comment by thecrypticace** [comment]
@AR10Dev I just merged the fix for this. It'll go out in the next tagged release of Tailwind CSS. Ultimately though Tauri is doing something really weird here. Node and _most_ of the code run in it thinks the working directory is one thing but it's actually been changed outside of node. This causes `path.resolve()` (one way of converting relative paths to absolute paths) to use one path as the working directory and the file system calls to use a different working directory since they result in a syscall.

Tauri should really _not_ be doing this. There should be some split process model so that Tauri doesn't affect the CWD of the node process but of a child process instead. I don't know enough about Tauri but this might be a good issue to open up with them.
